[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

# Disable event_loop fixture warning
# The pytest_asyncio event_loop doesn't play nice 
# with the pytest testclient
filterwarnings = [
"ignore:The event_loop fixture:DeprecationWarning"
]
